config/routes.rb
Rails.application.routes.draw do

  get 'home/content'
  get "content/edit" => 'content#edit', :as => :edit

  get  '/set-captain',   to: 'roles#setCaptain',      as: "set_captain"
  get  '/set-mentor',    to: 'roles#setMentor' ,      as: "set_mentor"

  get  '/delete-mentor', to: 'roles#destroyMentor',   as: "del_mentor"
  get  '/delete-member', to: 'roles#destroyMember',   as: "del_member"

  get  '/join-group',    to: 'join_groups#joinGroup', as: "join_group"
  get  '/leave-group',    to: 'join_groups#leaveGroup', as: "leave_group"

  get  '/approve-content',    to: 'pendings#approveContent', as: "approve_content"
  get  '/decline-content',    to: 'pendings#declineContent', as: "decline_content"

  get  '/approve-member',    to: 'pendings#approveMember', as: "approve_member"
  get  '/decline-member',    to: 'pendings#declineMember', as: "decline_member"

  post  '/create-attendance',    to: 'attendances#create', as: "attendance_member"

  post  '/event-attendance',    to: 'attendances#eventAtendance', as: "attendance_event_member"
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  mount Ckeditor::Engine => '/ckeditor'

  resources :users, only: [:show,:update, :index]
  resources :attendances
  resources :groups do
    resources :contents,   except: [:show, :index]
    resources :members,    only: [:index, :create]
    resources :attendances
    resources :pendings
    resources :settings,    only: [:index]
    resources :events
  end
  resources :courses
  resources :details
end

app/models/group.rb
class Group < ApplicationRecord
    validates :name,        presence: true, uniqueness: true, length: { maximum: 64   }
    validates :decription,  presence: true,  length: { maximum: 255  }
    validates :startdate, presence: true
    mount_uploader :picture, PictureUploader
    mount_uploader :cover, CoverUploader
    belongs_to :course
    has_many :contents
    has_many :events
    has_many :roles, :dependent => :destroy
    has_many :users, through: :roles


    scope :running_by_course, -> (course_id) {
      where(course_id: course_id).where("startdate <= ?", Date.today)
    }

    scope :comming_by_course, ->(course_id) {
      where(course_id: course_id).where("startdate > ?", Date.today)
    }


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout "layout_group", only: [:show]
  before_action :logged_in_user, only: [:create]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @cours    = Course.find_by(id: params[:course_id])
    @running  = Group.running_by_course(params[:course_id])
    @comming  = Group.comming_by_course(params[:course_id])
  end

  def new
  end

  def show
      @group = Group.find_by(id: params[:id])
      @course = Course.find_by(id: @group.course_id)
      @members_active = Role.where( status:1, group_id: params[:id])
      @members_isprove = Role.where(status:3, group_id: params[:id])
      @attendances = Attendance.all
      @contents = Content.where(group_id: @group.id,status: 1).order("endDate DESC","startDate DESC")
  end

  def create
    @course = Course.find_by(name: params[:group][:course_name])
    if !@course.nil?
      @group = Group.new(group_params)
      @group.slug = to_slug(params[:group][:name])
      @group.course_id = @course.id
      @group.save
      if @group.save
        @role = Role.new
        @role.user_id = current_user.id
        @role.group_id = @group.id
        @role.roles = 1
        @role.status = 1
        @role.save
        flash[:success] = "Create new groups successfully"
        redirect_to group_members_path(@group)
      else
        flash[:danger] = "Create new groups fail. Name not UNIQUE"
        redirect_to root_path
      end
    else
      @course = Course.create(name: params[:group][:course_name], user_id: current_user.id)
      @group = Group.new(group_params)
      @group.slug = to_slug(params[:group][:name])
      @group.course_id = @course.id
      @group.save
      if @group.save
        @role = Role.new
        @role.user_id = current_user.id
        @role.group_id = @group.id
        @role.roles = 1
        @role.status = 1
        @role.save
        flash[:success] = "Create new groups successfully"
        redirect_to group_members_path(@group)
      else
        flash[:danger] = "Create new groups fail. Name not UNIQUE"
        redirect_to root_path
      end
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = "Group updated"
      redirect_to @group
    else
      flash.now[:danger] = "Group don't updated"
      redirect_to group_settings_path(@group)
    end
  end
  private
  def group_params
    params.require(:group).permit :name, :decription, :startdate, :picture, :cover
  end

  def logged_in_user
    unless user_signed_in?
        flash[:danger] = "Please Log In"
        redirect_to root_path
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper

  def user_joined_in_group?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, status: 1).blank?
    end
  end

  def user_pending_in_group?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, status: 2).blank?
    end
  end

  def user_is_captain?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, roles: 1).blank?
    end
  end

end

app/views/groups/create.js.erb
$("#errors_div").html("<%= @resource.errors.full_messages %>")

app/views/groups/index.html.erb
 <div class="main-list-group container-fluid">
        <div class="row">
            <div class="cate">
               <h3>Home / <%= @cours.name %></h3>
               <hr>
            </div>
        </div>
        <!-- Comming Soon -->
        <div class="row">
            <div class="container">
                <div class="row">
                    <div class="list-group col-md-4">
                        <h3> Group Comming Soon</h3>
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4"></div>
                </div>
                <div class="row">
                    <% @comming.each do |comming| %>
                    <div class="item-group">
                        <div class="form-item">
                            <div class="g-top">
                                <%= link_to  comming.name, group_url(id: comming.id, group_id: comming.id), class: "link_group" %>
                            </div>
                            <hr>
                            <div class="g-mid">
                                <div class="g-m-left">
                                    <p><span class="glyphicon glyphicon-user" aria-hidden="true"></span> 1 Member</p>
                                    <p><span class="glyphicon glyphicon-tags" aria-hidden="true"></span>  0 Event</p>
                                </div>
                                <div class="g-m-right">
                                    <p><span class="glyphicon glyphicon-star" aria-hidden="true"></span> Nguyen Tuan Kiet</p>
                                    <p><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span><%= comming.startdate %></p>
                                </div>
                            </div>
                            <hr>
                            <div class="g-bottom">
                                <p><%= comming.decription %></p>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>


        <!-- end -comming soon -->
         <div class="row">
            <div class="container">
                <div class="row">
                    <div class="list-group col-md-4">
                        <h3> Group Running</h3>
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4"></div>
                </div>
                <div class="row">
                    <% @running.each do |gr| %>
                        <div class="item-group">
                            <div class="form-item">
                                <div class="g-top">
                                  <%= link_to  gr.name, group_url(id: gr.id, group_id: gr.id), class: "link_group" %>
                                </div>
                                <hr>
                                <div class="g-mid">
                                    <div class="g-m-left">
                                        <p><span class="glyphicon glyphicon-user" aria-hidden="true"></span> 1 Member</p>
                                        <p><span class="glyphicon glyphicon-tags" aria-hidden="true"></span>  0 Event</p>
                                    </div>
                                    <div class="g-m-right">
                                        <p><span class="glyphicon glyphicon-star" aria-hidden="true"></span> Nguyen Tuan Kiet</p>
                                        <p><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                                            <%= gr.startdate %>
                                        </p>
                                    </div>
                                </div>
                                <hr>
                                <div class="g-bottom">
                                    <p><%= gr.decription %></p>
                                </div>
                            </div>
                        </div>
                    <% end %>
            </div>
        </div>
        <!-- Running -->

    </div>

app/views/groups/show.html.erb
<% if user_signed_in? %>
<div class="row">
  <div class=" col-sm-8 col-sm-offset-1">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= link_to "Add content", new_group_content_path(@group), class: "btn btn-lg btn-default" %>
      </li>
      <li class="nav-item">
        <%= link_to "Or view  exsting contents", group_path, class: "btn btn-lg btn-default" %>
      </li>
    </ul>
  </div>
</div>

<% if @contents.blank? %>
<h2 align="center">No Content just yet, would you like to add the first!</h2>
<% else %>
<% @contents.each do |content| %>
<div class="row">
  <div class="well col-xs-8 col-xs-offset-1 col-content">
    <div class="row">
      <div class="col-xs-4">
        <div>
          <%= image_tag( "ava.jpg", alt: "Rails", class: "background-image-content" )%>
        </div>
        <div class="content-group">
          <div class="content-email">

            <div class="content-status">
              <% if content.endDate >= Date.today %>
              <h3 align="center">Learning</h3>
              <% else %>
              <h3 align="center">Done</h3>
              <% end %>
            </div>

            <span>
              <img src="<%= content.user.pictures%>" alt="" id="avatar">
              <%= content.user.fullname %> <br>
              <div class="content-create-sz">
                <%= content.created_at.strftime("%H:%M %d/%m/%Y") %>
              </div>
            </span>
          </div>
          <div class="content-date-join">
            <div class="content-create-sz">
              <span> Start:
                <%=  content.startDate.strftime("%d/%m/%Y") %></span>
              </br>
              <span>End:
                <%=  content.endDate.strftime("%d/%m/%Y") %></span>
              </br>
              <span>Level:
                <%=  content.level %></span>
            </div>
          </div>
          <div class="content-actions">
            <div class="content-button">
               <div>
                    <button class="btn btn-info" data-toggle="modal" data-backdrop="static"
                            data-keyboard="true" data-target="#attendanceContent<%=  content.id %>">Take
                        attendance
                    </button>
                </div>
                <!--Modal attendance-->
                <div id="attendanceContent<%=  content.id %>" class="modal" role="dialog">
                    <div class="modal-dialog modal-lg">

                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Attendance</h4>
                            </div>
                            <div class="modal-body">
                                <div>
                                  <%= form_for :member,  url: attendance_member_path do |f| %>
                                    <div class="row px-1">
                                        <div class="nav-attendance px-1">
                                            <div class="img-attendance">
                                                <%= image_tag("hero_1.jpg", alt: "Cover",id:"cover-header") %>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mt-2 my-2 py-2">
                                    <% @members_active.each do |member|%>
                                     
                                        <div class="member-attendance">
                                            <div class="row px-2">
                                                <div class="col-sm-7">
                                                    <div class="row">
                                                        <div class="col-sm-4 text-center">
                                                           <%= image_tag(member.user.pictures, alt: "Cover",class: "avt-attendance") %>
                                                        </div>
                                                        <div class="content col-sm-8">
                                                            <h4><%= member.user.fullname %></h4>
                                                            <div class="email-attendance"> <%= member.user.email %></div>
                                                            <div class="chx-attendance">
                                                      
                                                                  <input type="checkbox" name="member[<%= member.id %>][check]" value="yes" 
                                                                  <% @attendances.each do |attendance|%> 
                                                                  <%= "checked" if member.user_id == attendance.user_id && attendance.content_id == content.id && attendance.status == "1" %> 
                                                                  <% end %>
                                                                  > Present
                                                                <input type="hidden" name="member[<%= member.id %>][user_id]" value="<%= member.user.id %>">
                                                                <input type="hidden"name="member[<%= member.id %>][content_id]" value="<%= content.id %>">
                                                                <input type="hidden"name="member[<%= member.id %>][group_id]" value="<%= member.group.id %>">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-5 ">
                                                    <div class="input-note">
                                                        <input type="text" name="member[<%= member.id %>][note]" class="" placeholder="Note">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                            
                                      
                                    <% end %>

                                     <% @members_isprove.each do |member|%>
                                      <% @attendances.each do |attendance|%> 
                                       <% if member.user_id == attendance.user_id && attendance.content_id == content.id%>
                                        <div class="member-attendance">
                                            <div class="row px-2">
                                                <div class="col-sm-7">
                                                    <div class="row">
                                                        <div class="col-sm-4 text-center">
                                                           <%= image_tag(member.user.pictures, alt: "Cover",class: "avt-attendance") %>
                                                        </div>
                                                        <div class="content col-sm-8">
                                                            <h4><%= member.user.fullname %></h4>
                                                            <div class="email-attendance"> <%= member.user.email %></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-5 ">
                                                    <div class="input-note">
                                                        <input type="text" class="" placeholder="member out Group" readonly >
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <% end %>
                                      <% end %>
                                    <% end %>



                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                       <%= f.submit "Submit", class: 'btn btn-success' %>
                                    </div>
                                  <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end Modal attendance-->
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-8">
        <div class="row">
          <div class="col-xs-8">
            <div class="content-title">
              <%= truncate(content.title, length: 36) %>
            </div>
          </div>
          <div class="col-xs-4">
            <div class="menu-content-drop">
              <div class="dropdown">
                <button class="btn dropdown-toggle" id="dropdownMenu" data-toggle="dropdown"
                  style="position: absolute;right: 0">
                  ...
                </button>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit", edit_group_content_path(content.group, content), class: "btn btn-light", remote:true %></li>
                  <li>
                    <%= link_to "Delete", [content.group, content], class: "btn btn-light", method: :delete, data: { confirm: "Are you sure you want to delete this content?"}%>
                  </li>
                  <li><%= link_to "Create Event", new_group_event_path(content_id: content.id, group_id: content.group.id, titile: content.title), class: "btn btn-light", remote:true %></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="content-body ">
              <div class="col-xs-10 text-justify">
                  <% if content.description.length > 300 %>
                    <%= sanitize(content.description[0..300]+".....") %>
                    <%= link_to_function 'View all', "$(this).parent().html('#{escape_javascript sanitize(content.description)}')", id: "view-all",class: "btn-xs btn-info" %>
                  <% else %>
                    <%= sanitize(content.description) %>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<div id="product-modal" class="modal fade"></div>
<div id='remote_container'></div>
<% end %>
<% end %>
<% end %>