config/routes.rb
Rails.application.routes.draw do

  get 'home/content'
  get "content/edit" => 'content#edit', :as => :edit

  get  '/set-captain',   to: 'roles#setCaptain',      as: "set_captain"
  get  '/set-mentor',    to: 'roles#setMentor' ,      as: "set_mentor"

  get  '/delete-mentor', to: 'roles#destroyMentor',   as: "del_mentor"
  get  '/delete-member', to: 'roles#destroyMember',   as: "del_member"

  get  '/join-group',    to: 'join_groups#joinGroup', as: "join_group"
  get  '/leave-group',    to: 'join_groups#leaveGroup', as: "leave_group"

  get  '/approve-content',    to: 'pendings#approveContent', as: "approve_content"
  get  '/decline-content',    to: 'pendings#declineContent', as: "decline_content"

  get  '/approve-member',    to: 'pendings#approveMember', as: "approve_member"
  get  '/decline-member',    to: 'pendings#declineMember', as: "decline_member"

  post  '/create-attendance',    to: 'attendances#create', as: "attendance_member"

  post  '/event-attendance',    to: 'attendances#eventAtendance', as: "attendance_event_member"
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  mount Ckeditor::Engine => '/ckeditor'

  resources :users, only: [:show,:update, :index]
  resources :attendances
  resources :groups do
    resources :contents,   except: [:show, :index]
    resources :members,    only: [:index, :create]
    resources :attendances
    resources :pendings
    resources :settings,    only: [:index]
    resources :events
  end
  resources :courses
  resources :details
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :content
  belongs_to :user

end

app/models/attendance_event.rb
class AttendanceEvent < ApplicationRecord
    
  belongs_to :event
  belongs_to :user

end

app/models/content.rb
class Content < ApplicationRecord
  validates_presence_of :title, message: 'Title can not be blank'
  validates :title, length: { minimum: 6, maximum: 64 }
  validates_presence_of :description, message: 'description can not be blank'
  validates_presence_of :startDate, message: 'StartDate can not be blank'
  validates_presence_of :endDate, message: 'endDate can not be blank'
  validates_presence_of :level, message: 'endDate can not be blank'
  #validate :valid_start_date
  validate :valid_end_date
  
  belongs_to :user
  belongs_to :group
  has_many :attendances
  
  private
    def valid_start_date
      errors.add(:startDate, "Start date cannot be less than today") if startDate < Date.today
    end
  
    def valid_end_date
      errors.add(:endDate, "End date cannot be less than start date") if endDate < startDate
    end
  
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length: { maximum: 64   }

    has_many :groups
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, length: {maximum: 64 }
  validates :something, length: {maximum: 255 }
  validates :document, format: URI::regexp(%w[http https])
  validates_presence_of :speaker, message: 'Speaker can not be blank'
  validates :speaker, length: {maximum: 32 }
  validates_presence_of :startDate, message: 'StartDate can not be blank'
  #validate :valid_start_date

  belongs_to :group

  before_save :caculate_end_date

  private

  def caculate_end_date
    self.endDate = startDate + duration.to_f.hours
  end

  def valid_start_date
    errors.add(:startDate, "Start date cannot be less than today") if startDate < Date.today
  end

end

app/models/group.rb
class Group < ApplicationRecord
    validates :name,        presence: true, uniqueness: true, length: { maximum: 64   }
    validates :decription,  presence: true,  length: { maximum: 255  }
    validates :startdate, presence: true
    mount_uploader :picture, PictureUploader
    mount_uploader :cover, CoverUploader
    belongs_to :course
    has_many :contents
    has_many :events
    has_many :roles, :dependent => :destroy
    has_many :users, through: :roles


    scope :running_by_course, -> (course_id) {
      where(course_id: course_id).where("startdate <= ?", Date.today)
    }

    scope :comming_by_course, ->(course_id) {
      where(course_id: course_id).where("startdate > ?", Date.today)
    }


end

app/models/role.rb
class Role < ApplicationRecord

  belongs_to :group
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :validatable,:omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :contents
  has_many :roles, :dependent => :destroy
  has_many :groups, through: :roles
  has_many :attendances
  
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.email = auth.info.email
          user.password = Devise.friendly_token[0,20]
          user.fullname = auth.info.name
          user.pictures = auth.info.image
          user.givenname = auth.info.first_name
          user.save
      end
  end

  private
  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def group
        @group ||= Group.new
    end
    
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
  def Status

  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
   def user_is_captain_event?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, roles: 1).blank?
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper

  def user_joined_in_group?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, status: 1).blank?
    end
  end

  def user_pending_in_group?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, status: 2).blank?
    end
  end

  def user_is_captain?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, roles: 1).blank?
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper

    # def user_joined_in_group?
    #     if user_signed_in?
    #       !Role.where(user_id: current_user.id, group_id: params[:group_id], status: 1).blank?
    #     end
    #   end
    
    #   def user_pending_in_group?
    #     if user_signed_in?
    #       !Role.where(user_id: current_user.id, group_id: params[:group_id], status: 2).blank?
    #     end
    #   end
      
end

app/helpers/pendings_helper.rb
module PendingsHelper

    def pending_item
        @contents_pending = Content.where(group_id: @group.id, status: 2)
        @members_pending = Role.where(group_id: @group.id, status: 2)
        @pending_item = @contents_pending.size + @members_pending.size 
    end

    def role_permiss?
       
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def to_slug string
        string.parameterize.truncate 80, omission: ""
      end
      
end

app/views/home/content.html.erb
<h1>Showing selected Content</h1>
 <%= link_to "New Content", new_content_path %>

app/views/home/index.html.erb
<!-- main -->
    <div id="main">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-lg-1 main-left"></div>
                <div class="col-sm-6 col-lg-7 main-mid">
                    <div class="box-main">
                        <h2>Course</h2>
                        <ul>
                            <% @course.each do |course| %>
                                <li class="course"><%= link_to  course.name, groups_url(course_id: course.id) %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-lg-4 main-right">
                    <div class="box-main">
                        <h3 class="card-header" id="monthAndYear"></h3>
                        <table class="table table-bordered table-responsive-sm" id="calendar">
                            <thead>
                                <tr>
                                    <th>Sun</th>
                                    <th>Mon</th>
                                    <th>Tue</th>
                                    <th>Wed</th>
                                    <th>Thu</th>
                                    <th>Fri</th>
                                    <th>Sat</th>
                                </tr>
                            </thead>

                            <tbody id="calendar-body">

                            </tbody>
                        </table>

                        <div class="form-inline">

                            <button class="btn btn-outline-primary col-sm-6" id="previous"
                                onclick="previous()">Previous</button>

                            <button class="btn btn-outline-primary col-sm-6" id="next" onclick="next()">Next</button>
                        </div>
                        <br />
                        <form class="form-inline">
                            <label class="lead mr-2 ml-2" for="month"> Jump To: </label>
                            <select class="form-control col-sm-4" name="month" id="month" onchange="jump()">
                                <option value=0>Jan</option>
                                <option value=1>Feb</option>
                                <option value=2>Mar</option>
                                <option value=3>Apr</option>
                                <option value=4>May</option>
                                <option value=5>Jun</option>
                                <option value=6>Jul</option>
                                <option value=7>Aug</option>
                                <option value=8>Sep</option>
                                <option value=9>Oct</option>
                                <option value=10>Nov</option>
                                <option value=11>Dec</option>
                            </select>


                            <label for="year"></label><select class="form-control col-sm-4" name="year" id="year"
                                onchange="jump()">
                                <option value=1990>1990</option>
                                <option value=1991>1991</option>
                                <option value=1992>1992</option>
                                <option value=1993>1993</option>
                                <option value=1994>1994</option>
                                <option value=1995>1995</option>
                                <option value=1996>1996</option>
                                <option value=1997>1997</option>
                                <option value=1998>1998</option>
                                <option value=1999>1999</option>
                                <option value=2000>2000</option>
                                <option value=2001>2001</option>
                                <option value=2002>2002</option>
                                <option value=2003>2003</option>
                                <option value=2004>2004</option>
                                <option value=2005>2005</option>
                                <option value=2006>2006</option>
                                <option value=2007>2007</option>
                                <option value=2008>2008</option>
                                <option value=2009>2009</option>
                                <option value=2010>2010</option>
                                <option value=2011>2011</option>
                                <option value=2012>2012</option>
                                <option value=2013>2013</option>
                                <option value=2014>2014</option>
                                <option value=2015>2015</option>
                                <option value=2016>2016</option>
                                <option value=2017>2017</option>
                                <option value=2018>2018</option>
                                <option value=2019>2019</option>
                                <option value=2020>2020</option>
                                <option value=2021>2021</option>
                                <option value=2022>2022</option>
                                <option value=2023>2023</option>
                                <option value=2024>2024</option>
                                <option value=2025>2025</option>
                                <option value=2026>2026</option>
                                <option value=2027>2027</option>
                                <option value=2028>2028</option>
                                <option value=2029>2029</option>
                                <option value=2030>2030</option>
                            </select></form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- end main -->