config/routes.rb
Rails.application.routes.draw do

  get 'home/content'
  get "content/edit" => 'content#edit', :as => :edit

  get  '/set-captain',   to: 'roles#setCaptain',      as: "set_captain"
  get  '/set-mentor',    to: 'roles#setMentor' ,      as: "set_mentor"

  get  '/delete-mentor', to: 'roles#destroyMentor',   as: "del_mentor"
  get  '/delete-member', to: 'roles#destroyMember',   as: "del_member"

  get  '/join-group',    to: 'join_groups#joinGroup', as: "join_group"
  get  '/leave-group',    to: 'join_groups#leaveGroup', as: "leave_group"

  get  '/approve-content',    to: 'pendings#approveContent', as: "approve_content"
  get  '/decline-content',    to: 'pendings#declineContent', as: "decline_content"

  get  '/approve-member',    to: 'pendings#approveMember', as: "approve_member"
  get  '/decline-member',    to: 'pendings#declineMember', as: "decline_member"

  post  '/create-attendance',    to: 'attendances#create', as: "attendance_member"

  post  '/event-attendance',    to: 'attendances#eventAtendance', as: "attendance_event_member"
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  mount Ckeditor::Engine => '/ckeditor'

  resources :users, only: [:show,:update, :index]
  resources :attendances
  resources :groups do
    resources :contents,   except: [:show, :index]
    resources :members,    only: [:index, :create]
    resources :attendances
    resources :pendings
    resources :settings,    only: [:index]
    resources :events
  end
  resources :courses
  resources :details
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, length: {maximum: 64 }
  validates :something, length: {maximum: 255 }
  validates :document, format: URI::regexp(%w[http https])
  validates_presence_of :speaker, message: 'Speaker can not be blank'
  validates :speaker, length: {maximum: 32 }
  validates_presence_of :startDate, message: 'StartDate can not be blank'
  #validate :valid_start_date

  belongs_to :group

  before_save :caculate_end_date

  private

  def caculate_end_date
    self.endDate = startDate + duration.to_f.hours
  end

  def valid_start_date
    errors.add(:startDate, "Start date cannot be less than today") if startDate < Date.today
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_start_date, only: [:create]
  layout "layout_group"

  def index
        @group = Group.find_by(id: params[:group_id])
        @events = Event.where(group_id: params[:group_id])
        @eventsdone = Event.where(group_id: params[:group_id]).where('endDate <= ?',Time.now).order("endDate DESC")
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
    @members_active = Role.where( status:1, group_id: params[:group_id])
    @members_isprove = Role.where(status:3, group_id: params[:group_id])
    @attendances = AttendanceEvent.all
  end

  def create
    if !Role.where(user_id: current_user.id, group_id: params[:event][:group_id], roles: 1).blank?
          @event = Event.new(event_params)
            if !params[:event][:content_id].blank?
              @event.startDate = params[:event][:startDate]
              @event.color = "Red"
            else
              @event.startDate = @full_date
            end
          @event.save
          flash.now[:success] = "Create event successfully"
    else
          flash.now[:danger] = "you don't have the right to create event"
    end
  end

  def update
    @event.startDate = params[:event][:startDate]
    if @event.update(event_params)
      flash[:success] = "Event was updated"
    else
      flash[:danger] = "Event was not updated"
    end
  end


  def destroy
    @event.destroy
  end

  private

  def set_event
      @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :something, :document,
                                          :speaker, :color, :duration,
                                          :group_id, :content_id)
  end

  def set_start_date
    @date = params.dig(:event, :startDate2) + " " + params.dig(:event, :startDate)
    @full_date = Time.zone.parse(@date)
  end


end

app/helpers/events_helper.rb
module EventsHelper
   def user_is_captain_event?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, roles: 1).blank?
    end
  end
end

app/views/events/_edit.html.erb
<div class="modal fade" id="edit_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">

          <div class="row">
            <div class="col-md-8">
              <h4 class="modal-title"><%= @event.title %></h4>
            </div>
              <div class="col-md-4">
              <div class="row">
                <% if @event.endDate >= Date.today %>
                  <div class="control-label col-sm-3">
                  </div>
                  <div class="control-label col-sm-1">
                    <a class="glyphicon glyphicon-edit" data-toggle="modal" data-target="#myModal<%=  @event.id %>"></a>
                  </div>
                  <div class="col-md-1">
                    <a class="glyphicon glyphicon-pencil" data-toggle="modal" data-target="#exampleModal"></a>
                  </div>
                  <div class="col-md-1">
                    <%= link_to "", group_event_path(@event),class: "glyphicon glyphicon-trash", method: :delete, data: { confirm: 'Are you sure to delete  this event?' },remote: true %>
                  </div>
                  <div class="col-md-3">
                    <button type="button" class="close glyphicon glyphicon-remove" data-dismiss="modal"></button>
                  </div>
                <% else %>
                  <div class="control-label col-sm-3">
                  </div>
                  <div class="control-label col-sm-1">
                  </div>
                  <div class="col-md-1">
                  </div>
                  <div class="col-md-1">
                  </div>
                  <div class="col-md-3">
                    <button type="button" class="close glyphicon glyphicon-remove" data-dismiss="modal"></button>
                  </div>
                <% end %>
              </div>
          </div>
      </div>
    </div>

      <div class="modal-body">
        <%= render 'show', event: @event %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <%= render 'formedit', event: @event %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
 <!--Modal attendance-->
    <div id="myModal<%=  @event.id %>" class="modal" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Attendance</h4>
                </div>
                <div class="modal-body">
                    <div>
                        <%= form_for :member,  url: attendance_event_member_path do |f| %>
                        <div class="row px-1">
                            <div class="nav-attendance px-1">
                                <div class="img-attendance">
                                    <%= image_tag("hero_1.jpg", alt: "Cover",id:"cover-header") %>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-2 my-2 py-2">
                        <% @members_active.each do |member|%>
                            
                            <div class="member-attendance">
                                <div class="row px-2">
                                    <div class="col-sm-7">
                                        <div class="row">
                                            <div class="col-sm-4 text-center">
                                                <%= image_tag(member.user.pictures, alt: "Cover",class: "avt-attendance") %>
                                            </div>
                                            <div class="content col-sm-8">
                                                <h4><%= member.user.fullname %></h4>
                                                <div class="email-attendance"> <%= member.user.email %></div>
                                                <div class="chx-attendance">
                                            
                                                        <input type="checkbox" name="member[<%= member.id %>][check]" value="yes" 
                                                        <% @attendances.each do |attendance|%> 
                                                        <%= "checked" if member.user_id == attendance.user_id && attendance.event_id ==  @event.id && attendance.status == "1" %> 
                                                        <% end %>
                                                        > Present
                                                    <input type="hidden" name="member[<%= member.id %>][user_id]" value="<%= member.user.id %>">
                                                    <input type="hidden"name="member[<%= member.id %>][event_id]" value="<%=  @event.id %>">
                                                    <input type="hidden"name="member[<%= member.id %>][group_id]" value="<%= member.group.id %>">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-5 ">
                                        <div class="input-note">
                                            <input type="text" name="member[<%= member.id %>][note]" class="" placeholder="Note">
                                        </div>
                                    </div>
                                </div>
                            </div>
                
                            
                        <% end %>

                            <% @members_isprove.each do |member|%>
                            <% @attendances.each do |attendance|%> 
                            <% if member.user_id == attendance.user_id && attendance.event_id ==  @event.id%>
                            <div class="member-attendance">
                                <div class="row px-2">
                                    <div class="col-sm-7">
                                        <div class="row">
                                            <div class="col-sm-4 text-center">
                                                <%= image_tag(member.user.pictures, alt: "Cover",class: "avt-attendance") %>
                                            </div>
                                            <div class="content col-sm-8">
                                                <h4><%= member.user.fullname %></h4>
                                                <div class="email-attendance"> <%= member.user.email %></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-5 ">
                                        <div class="input-note">
                                            <input type="text" class="" placeholder="member out Group" readonly >
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <% end %>
                            <% end %>
                        <% end %>



                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                            <%= f.submit "Submit", class: 'btn btn-success' %>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--end Modal attendance-->

app/views/events/_form.html.erb
<%= form_for [:group, @event], remote:true do |f| %>
  <%= f.hidden_field :group_id, value: params[:group_id] %>
  <%= f.hidden_field :content_id, value: params[:content_id] %>
  <%= f.hidden_field :startDate2, value: params[:startDate] %>
  <%= f.hidden_field :startDate3, value: params[:startDate3] %>
<div class="row">
  <div class="control-label col-sm-12">
    <div class="event-form-pading">
      <%= f.text_field :title, class:"form-control", placeholder: "Title", value: params[:title] %>
    </div>
    <div class="event-form-pading">
      <%=f.text_area :something,rows: 5, class: "form-control", placeholder: "Something about your event"  %>
    </div>
    <div class="event-form-pading">
      <%= f.text_field :document, class:"form-control", placeholder: "Document Link " %>
    </div>
    <div class="event-form-pading">
      <%= f.text_field :speaker, class:"form-control", placeholder: "Speaker",required: true  %>
    </div>
    <div class="row">
      <div class="control-label col-sm-6">
        <div class="event-form-pading">
         <%=f.time_field :startDate, class: "form-control",placeholder: "Start Date",required: true   %>
        </div>
          <script>
              $('.datetimepicker').datepicker({format: 'dd/mm/yyyy', startDate: '0d'});

          </script>
      </div>
      <div class="control-label col-sm-6">
        <div class="event-form-pading-select">

        <%= f.select :duration, [[ '25 minutes', '0.42' ],[ '1 hours 25 minutes', '1.42'],[ '2 hours 25 minutes', '2.42']],{}, {class: "js-example-tags select3"}  %>

          <script type="text/javascript">
             $(".js-example-tags").select2({tags: true});
          </script>

        </div>
      </div>
    </div>
  </div>
</div>

  <div class="event-button">
 <button type="button" class="btn btn-danger" data-dismiss="modal" >Cancel</button>
  <%= f.submit "Add", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/events/_formContent.html.erb
<%= form_for [:group, @event], remote:true do |f| %>
  <%= f.hidden_field :group_id, value: params[:group_id] %>
  <%= f.hidden_field :content_id, value: params[:content_id] %>
  <%= f.hidden_field :startDate2, value: params[:startDate] %>
<div class="row">
  <div class="control-label col-sm-12">
    <div class="event-form-pading">
      <%= f.text_field :title, class:"form-control", placeholder: "Title", value: params[:title]%>
    </div>
    <div class="event-form-pading">
      <%=f.text_area :something,rows: 5, class: "form-control", placeholder: "Something about your event" %>
    </div>
    <div class="event-form-pading">
      <%= f.text_field :document, class:"form-control", placeholder: "Document Link "  %>
    </div>
    <div class="event-form-pading">
      <%= f.text_field :speaker, class:"form-control", placeholder: "Speaker",required: true  %>
    </div>
    <div class="row">
      <div class="control-label col-sm-6">
        <div class="event-form-pading">
         <%=f.datetime_field :startDate, class: "form-control",placeholder: "Start Date"  %>
        </div>
          <script>
              $('.datetimepicker').datepicker({format: 'dd/mm/yyyy', startDate: '0d'});
          </script>
      </div>
      <div class="control-label col-sm-6">
        <div class="event-form-pading-select">

        <%= f.select :duration, [[ '25 minutes', '0.42' ],[ '1 hour 25 minutes', '1.42'],[ '2 hour 25 minutes', '2.42']],{}, {class: "js-example-tags select3"}  %>

          <script type="text/javascript">
             $(".js-example-tags").select2({tags: true});
          </script>

        </div>
      </div>
    </div>
  </div>
</div>

  <div class="event-button">
 <button type="button" class="btn btn-danger" data-dismiss="modal" >Cancel</button>
  <%= f.submit "Add", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/events/_formedit.html.erb
<%= form_for [:group, @event], validate:true, remote:true do |f| %>
  <%= f.hidden_field :content_id, value: params[:content_id] %>
<div class="row">
  <div class="control-label col-sm-12">
    <div class="event-form-pading">
      <%= f.text_field :title, class:"form-control", placeholder: "Title"%>
    </div>
    <div class="event-form-pading">
      <%=f.text_area :something,rows: 5, class: "form-control", placeholder: "Something about your event" %>
    </div>
    <div class="event-form-pading">
      <%= f.text_field :document, class:"form-control", placeholder: "Document Link "  %>
    </div>
    <div class="event-form-pading">
      <%= f.text_field :speaker, class:"form-control", placeholder: "Speaker",required: true  %>
    </div>
    <div class="row">
      <div class="control-label col-sm-6">
        <div class="event-form-pading">
         <%=f.datetime_field :startDate, class: "form-control",placeholder: "Start Date"  %>
        </div>
          <script>
              $('.datetimepicker').datepicker({format: 'dd/mm/yyyy', startDate: '0d'});
          </script>
      </div>
      <div class="control-label col-sm-6">
        <div class="event-form-pading-select">

        <%= f.select :duration, [[ '25 minutes', '0.42' ],[ '1 hour 25 minutes', '1.42'],[ '2 hour 25 minutes', '2.42']],{}, {class: "js-example-tags select3"}  %>

          <script type="text/javascript">
             $(".js-example-tags").select2({tags: true});
          </script>

        </div>
      </div>
    </div>
  </div>
</div>

  <div class="event-button">
 <button type="button" class="btn btn-danger" data-dismiss="modal" >Cancel</button>
  <%= f.submit "Add", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/events/_new.html.erb
<div class="modal fade" id="new_event" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create New Event</h4>
      </div>
      <div class="modal-body">
        <% if !@event.content_id = params[:content_id] %>
        <%= render 'form', event: @event %>
        <% else %>
        <%= render 'formContent', event: @event %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/_show.html.erb
<div >
              <div class="row">
                <div class="event-detail">
                  <div class="row">
                    <div class="col-sm-12">
                      <p><b>Title:</b> <%= @event.title %> </p>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12 text-justify ">
                      <h4><b> Something about your event: </b></h4>
                    <div class="pr-2">
                      <%= @event.something %>
                    </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <p><b>Document Link:</b> <%= @event.document %></p>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <p><b>Speaker:</b> <%= @event.speaker %></p>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <p><b>Start Date:</b> <%= @event.startDate.strftime("%H:%M %d/%m/%Y") %></p>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <p><b>End Date:</b> <%= @event.endDate.strftime("%H:%M %d/%m/%Y") %></p>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <p><b>Duration:</b> <%= @event.duration %> hours </p>
                    </div>
                  </div>
                </div>
              </div>
      </div>
  <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
  </div>

app/views/events/create.js.erb
$('.calendar').fullCalendar(
  'renderEvent',
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/events/destroy.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>])
$('.modal').modal('hide');

app/views/events/edit.js.erb
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_event').on('shown.bs.modal', '.modal', function() {
  $('form[data-client-side-validations]').enableClientSideValidations();
}).modal("show")

app/views/events/index.html.erb
<div class="container" id="calendar" data-group-id="<%= params[:group_id] %>" >
  <div class="row">
    <div class="col-md-1"></div>
    <!-- mid -->
    <div class="col-md-8">
      <div class="calendar"></div>

    </div>
    <!-- end mid -->
    <div class="col-md-1"></div>
  </div>
</div>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-8"><h1>HISTORY</h1></hr></div>
  </div>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-8">
      <% @eventsdone.each do |event| %>
       <p style="font-size: 12px" ><%= event.startDate %></p>
        <p style="color: #ffc107!important;font-size: 16px"><%= event.title %></p>
        <p><span style="font-weight:bold">Duration:</span> <%= event.duration %> hours</p>
        <p><span style="font-weight:bold">Speaker:</span><%= event.speaker %></p>
        <p style="font-size: 12px"><%= event.something %></p>
        <hr>
      <% end %>
    </div>
  </div>


<div id='remote_container'></div>

app/views/events/new.js.erb
$('#remote_container').html('<%= j render"new" %>');
//$('#new_event').modal('show');
$('#new_event').on('shown.bs.modal', function() {
  $('form[data-validate]').enableClientSideValidations();
}).modal("show")

app/views/events/show.js.erb
$('#remote_container').html('<%= j render"show" %>');
$('#show_event').modal('show');

app/views/events/update.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>]);
$('.calendar').fullCalendar(
  'renderEvent',
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');
location.reload();