config/routes.rb
Rails.application.routes.draw do

  get 'home/content'
  get "content/edit" => 'content#edit', :as => :edit

  get  '/set-captain',   to: 'roles#setCaptain',      as: "set_captain"
  get  '/set-mentor',    to: 'roles#setMentor' ,      as: "set_mentor"

  get  '/delete-mentor', to: 'roles#destroyMentor',   as: "del_mentor"
  get  '/delete-member', to: 'roles#destroyMember',   as: "del_member"

  get  '/join-group',    to: 'join_groups#joinGroup', as: "join_group"
  get  '/leave-group',    to: 'join_groups#leaveGroup', as: "leave_group"

  get  '/approve-content',    to: 'pendings#approveContent', as: "approve_content"
  get  '/decline-content',    to: 'pendings#declineContent', as: "decline_content"

  get  '/approve-member',    to: 'pendings#approveMember', as: "approve_member"
  get  '/decline-member',    to: 'pendings#declineMember', as: "decline_member"

  post  '/create-attendance',    to: 'attendances#create', as: "attendance_member"

  post  '/event-attendance',    to: 'attendances#eventAtendance', as: "attendance_event_member"
  root 'home#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  mount Ckeditor::Engine => '/ckeditor'

  resources :users, only: [:show,:update, :index]
  resources :attendances
  resources :groups do
    resources :contents,   except: [:show, :index]
    resources :members,    only: [:index, :create]
    resources :attendances
    resources :pendings
    resources :settings,    only: [:index]
    resources :events
  end
  resources :courses
  resources :details
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :content
  belongs_to :user

end

app/models/attendance_event.rb
class AttendanceEvent < ApplicationRecord
    
  belongs_to :event
  belongs_to :user

end

app/models/content.rb
class Content < ApplicationRecord
  validates_presence_of :title, message: 'Title can not be blank'
  validates :title, length: { minimum: 6, maximum: 64 }
  validates_presence_of :description, message: 'description can not be blank'
  validates_presence_of :startDate, message: 'StartDate can not be blank'
  validates_presence_of :endDate, message: 'endDate can not be blank'
  validates_presence_of :level, message: 'endDate can not be blank'
  #validate :valid_start_date
  validate :valid_end_date
  
  belongs_to :user
  belongs_to :group
  has_many :attendances
  
  private
    def valid_start_date
      errors.add(:startDate, "Start date cannot be less than today") if startDate < Date.today
    end
  
    def valid_end_date
      errors.add(:endDate, "End date cannot be less than start date") if endDate < startDate
    end
  
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length: { maximum: 64   }

    has_many :groups
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, length: {maximum: 64 }
  validates :something, length: {maximum: 255 }
  validates :document, format: URI::regexp(%w[http https])
  validates_presence_of :speaker, message: 'Speaker can not be blank'
  validates :speaker, length: {maximum: 32 }
  validates_presence_of :startDate, message: 'StartDate can not be blank'
  #validate :valid_start_date

  belongs_to :group

  before_save :caculate_end_date

  private

  def caculate_end_date
    self.endDate = startDate + duration.to_f.hours
  end

  def valid_start_date
    errors.add(:startDate, "Start date cannot be less than today") if startDate < Date.today
  end

end

app/models/group.rb
class Group < ApplicationRecord
    validates :name,        presence: true, uniqueness: true, length: { maximum: 64   }
    validates :decription,  presence: true,  length: { maximum: 255  }
    validates :startdate, presence: true
    mount_uploader :picture, PictureUploader
    mount_uploader :cover, CoverUploader
    belongs_to :course
    has_many :contents
    has_many :events
    has_many :roles, :dependent => :destroy
    has_many :users, through: :roles


    scope :running_by_course, -> (course_id) {
      where(course_id: course_id).where("startdate <= ?", Date.today)
    }

    scope :comming_by_course, ->(course_id) {
      where(course_id: course_id).where("startdate > ?", Date.today)
    }


end

app/models/role.rb
class Role < ApplicationRecord

  belongs_to :group
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :validatable,:omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :contents
  has_many :roles, :dependent => :destroy
  has_many :groups, through: :roles
  has_many :attendances
  
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.email = auth.info.email
          user.password = Devise.friendly_token[0,20]
          user.fullname = auth.info.name
          user.pictures = auth.info.image
          user.givenname = auth.info.first_name
          user.save
      end
  end

  private
  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def group
        @group ||= Group.new
    end
    
end

app/helpers/contents_helper.rb
module ContentsHelper
  def Status

  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
   def user_is_captain_event?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, roles: 1).blank?
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper

  def user_joined_in_group?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, status: 1).blank?
    end
  end

  def user_pending_in_group?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, status: 2).blank?
    end
  end

  def user_is_captain?
    if user_signed_in?
      !Role.where(user_id: current_user.id, group_id: @group.id, roles: 1).blank?
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper

    # def user_joined_in_group?
    #     if user_signed_in?
    #       !Role.where(user_id: current_user.id, group_id: params[:group_id], status: 1).blank?
    #     end
    #   end
    
    #   def user_pending_in_group?
    #     if user_signed_in?
    #       !Role.where(user_id: current_user.id, group_id: params[:group_id], status: 2).blank?
    #     end
    #   end
      
end

app/helpers/pendings_helper.rb
module PendingsHelper

    def pending_item
        @contents_pending = Content.where(group_id: @group.id, status: 2)
        @members_pending = Role.where(group_id: @group.id, status: 2)
        @pending_item = @contents_pending.size + @members_pending.size 
    end

    def role_permiss?
       
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def to_slug string
        string.parameterize.truncate 80, omission: ""
      end
      
end

app/views/layouts/_footer.html.erb
   <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center sp-60">
                    <img src="img/only-logo.png" alt="">
                </div>
            </div>
            <div class="row p-37">
                <div class="col-lg-4">
                    <div class="about-footer">
                        <h5>About Homes</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eleifend tristique venenatis.
                            Maecenas a rutrum tellus nam vel semper nibh.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="footer-blog">
                        <h5>Latest Blog Posts</h5>

                        <div class="single-blog">
                            <div class="rt-side">
                                <h6>How to find the perfect area for<br> your next house.</h6>
                            </div>
                        </div>
                        <div class="single-blog">
                            <div class="rt-side">
                                <h6>How to find the perfect area for<br> your next house.</h6>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="footer-address">
                        <h5>Get In Touch</h5>
                        <ul>
                            <li><span class="glyphicon glyphicon-map-marker"></span> <span> HH3 Sudico Me Tri, Ha Noi,
                                    Viet Nam</span>
                            </li>
                            <li><span class="glyphicon glyphicon-envelope"></span><span> ntq@ntq-solution.com</span>
                            </li>
                            <li><span class="glyphicon glyphicon-flag"><span> 214-805-4428</span></li>
                        </ul>
                        <p>Monday – Friday: 9 am – 5 pm</p>
                        <p>Saturday: 9 am – 1pm</p>
                    </div>
                </div>
            </div>

            <div class="row p-20">
                <div class="col-lg-12 text-center">
                    <div class="copyright">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy; NTQ Solution
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

                    </div>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_header.html.erb
<div class="header_top">
    <div class="row">
        <div class="col-xs-12 col-sm-4" id="left">
            <%= link_to image_tag("lg.png", alt:"logo"), root_path %>
        </div>
        <div class="col-xs-12 col-sm-2" id="mid">
            <div class="flow">
                <div class="dropdown following">
                    <a class="dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">Following Classes
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu overflow" role="menu" aria-labelledby="menu1">
                    <% if user_signed_in? %>
                        <% @following.each do |follow| %>
                        <li><%= link_to  follow.name, group_path(follow) %></li>
                        <% end %>
                    <% end %>
                        <li role="presentation" class="divider"></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 " id="right">
            <ul>
                <li><a href="#">Help</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">FAQ</a></li>
                <% if user_signed_in? %>
                <li id="profile" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="<%= current_user.pictures%>" alt="" id="avatar">
                        <%= current_user.fullname %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to ' My Profile', user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li>  <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                    </ul>
                </li>
                <% else %>
                <li><%= link_to  "login", user_google_oauth2_omniauth_authorize_path %></li>
                <% end %>

            </ul>
        </div>
    </div>
</div>
<div class="header_bot">
    <div class="cover-image">
        <%= image_tag("cv.jpeg", alt: "Cover",id:"cover-header") %>
        <h2>Welcome to Learning social networking</h2>
            <% if user_signed_in? %>
           <button class="open-button" onclick="openForm()">Create new group</button>
            <div class="form-popup" id="myForm">
                <%= form_for(group, url: groups_path, html: {class: "form-container"}) do |f| %>
                    <h1>Create new group</h1>
                    <%= f.label :name, "Your group name" %>
                    <%= f.text_field :name, class: 'form-control',:required => true, maxlength: "64" %>
                    
                    <%= f.label :decription %>
                    <%= f.text_field :decription, class: 'form-control',:required => true, maxlength: "255" %>

                    <%= f.label :startdate, "Start Date" %>
                    <%= f.text_field :startdate, class: 'form-control datepicker',:required => true , placeholder: "Stat Date"%>

                    <%= f.label :course, "Course" , class: "course" %>
                    <select  name="group[course_name]"  class="js-example-tags select2">
                        <% @cour.each do |course| %>
                        <option id="select2" ><%= course.name %></option>
                        <% end %>
                    </select>
                    
                    <button type="button" class="btn cancel" onclick="closeForm()">Cancel</button>
                    <%= f.submit "Done and publish", class: "btn btn-primary" %>

                <% end %>
            </div>
            <script>
                 $('.datepicker').datepicker({format: 'dd/mm/yyyy', startDate: '0d'});
            </script>
            <script>

                function openForm() {
                    document.getElementById("myForm").style.display = "block";
                }

                function closeForm() {
                    document.getElementById("myForm").style.display = "none";
                }
                function myFunction() {
                    var popup = document.getElementById("myPopup");
                    popup.classList.toggle("show");
                }
            </script>
             <% end %>
    </div>
</div>

app/views/layouts/_header_group.html.erb
<div class="header_top">
    <div class="row">
        <div class="col-xs-12 col-sm-4" id="left">
            <%= link_to image_tag("lg.png", alt:"logo"), root_path %>
        </div>
        <div class="col-xs-12 col-sm-2" id="mid">
            <div class="flow">
                <div class="dropdown following">
                    <a class="dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">Following Classes
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu overflow" role="menu" aria-labelledby="menu1">
                        <% if user_signed_in? %>
                            <% @following.each do |follow| %>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"> <%= follow.name %></a></li>
                            <% end %>
                        <% end %>
                        <li role="presentation" class="divider"></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 " id="right">
            <ul>
                <li><a href="#">Help</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">FAQ</a></li>
                <% if user_signed_in? %>
                <li id="profile" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="<%= current_user.pictures%>" alt="" id="avatar">
                        <%= current_user.fullname %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to ' My Profile', user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li>  <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                    </ul>
                </li>
                <% else %>
                <li><%= link_to  "login", user_google_oauth2_omniauth_authorize_path %></li>
                <% end %>

            </ul>
        </div>
    </div>
</div>
<div class="header_bot">
    <div class="cover-image">
    <% if @group.cover.nil? || @group.cover.blank? %>
        <%= image_tag("hero_1.jpg", alt: "Cover",id:"cover-header") %>
    <% else %>
         <%= image_tag @group.cover.url %>
    <% end %>
    </div>
</div>
  <!-- menu group avatar group -->
    <div class="container">
        <div class="row" id="menuG">
            <div class="col-md-3">
                <div class="avatarGroup">
                 <% if @group.picture.nil? || @group.picture.blank?%>
                     <%= image_tag("ava.jpeg", alt: "Cover",id:"cover-header") %>
                <% else %>
                    <%= image_tag @group.picture.url %>
                <% end %>
                </div>
                <div class="camera">
                    <%= form_for @group do |f| %>
                    <%= f.label :picture, ".",class: "glyphicon glyphicon-camera", for: "avata" %>
                    <%= f.file_field :picture, id: "avata",class: "upload" %>
                    <% end %>
                </div>
                <div class="lean">
                <h2><%= @group.name %></h2>
                <% if user_signed_in? %>
                    <% if user_joined_in_group? %>
                    <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Joined
                        <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                          <li><%= link_to  "Leave Group", leave_group_path(user_id: current_user.id, group_id: @group.id) %></li>
                        </ul>
                    </div>
                    <% elsif  user_pending_in_group? %>
                        <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Pending
                        </div>
                    <% else %>
                       <button><%= link_to  "+ Want To Join", join_group_path(user_id: current_user.id, group_id: @group.id) %></button>
                    <% end %>
                <% end %>
                </div>
            </div>
            <div class="col-md-8">
                <div class="menugruop">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <%= link_to 'Contents', group_path(@group) %>
                        </li>
                        <li>
                            <%= link_to  "Member",  group_members_path(@group) %>
                        </li>
                        <li>
                            <%= link_to  "Attendance",  group_attendances_path(@group) %>
                        </li>
                        <li>
                            <%= link_to  "Calendar", group_events_path(group_id: @group.id) %>
                        </li>
                        <li>

                            <% if  user_is_captain? %>
                            <%= link_to  "Pending items", group_pendings_path(@group) %>
                             <% end %>
                        </li>
                        <li>
                        <% if  user_is_captain? %>
                            <%= link_to  "Setting", group_settings_path(@group) %>
                         <% end %>
                        </li>
                    </ul>
                </div>
            </div>
            <% if  user_is_captain? %>
            <div class="col-md-3" style= "width: 35px;border-radius: 100%; background-color: blue;color: #fff;height: 22px;right: 213px;top: -2px;">
                <span>
                    <% if pending_item %>
                        <%= @pending_item %>
                    <% end %>
                </span>
            </div>
            <% end %>
        </div>
    </div>
    <!-- end menu group avatar group -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningSocialNetwork</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <%= render 'shared/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <div id='remote_container'></div>
  </body>
</html>

app/views/layouts/layout_group.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningSocialNetwork</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
  </head>

  <body>
      <%= render 'layouts/header_group' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this object from being saved:
     </h2>
     <div class="panel-body">
      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, message| %>
<div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, message, :id => "flash_#{name}" if message.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>